language: dart
dart:
  - dev

jobs:
  include:
    - stage: valid
      name: "Dart Analyzer"
      os: linux
      script: dartanalyzer --enable-experiment=non-nullable --fatal-warnings --fatal-infos .
    - stage: valid
      name: "Dart Formatter"
      os: linux
      script: dartfmt --dry-run --set-exit-if-changed .
    - stage: test
      name: "VM Tests"
      os: linux
      script: pub run --enable-experiment=non-nullable test --platform vm
    - stage: test
      name: "Chrome Tests"
      os: linux
      script: pub run --enable-experiment=non-nullable test --platform chrome

stages:
  - valid
  - test
