name: more
version: 1.17.0

author: Lukas Renggli <renggli@gmail.com>
homepage: https://github.com/renggli/dart-more
description: More Dart — Literally. Collecting, iterating, caching, mathematics,
  matching, ordering, and formatting easily.

environment:
  sdk: '>=2.3.0 <3.0.0'
dependencies:
  collection: ^1.14.0
dev_dependencies:
  test: ^1.6.0
