name: more
version: 2.8.0-nullsafety

homepage: https://github.com/renggli/dart-more
description: More Dart — Literally. Collecting, iterating, caching, mathematics,
  matching, ordering, and formatting easily.

environment:
  sdk: '>=2.9.0 <3.0.0'
dependencies:
  characters: ^1.0.0-nullsafety
  collection: ^1.14.0-nullsafety
  meta: ^1.2.0-nullsafety
dev_dependencies:
  test: ^1.15.0-nullsafety
